const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('eql', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setClasses: (list) => ipcRenderer.invoke('classes:set', list),
  setTheme: (t) => ipcRenderer.invoke('theme:set', t),
  setLang: (c) => ipcRenderer.invoke('lang:set', c),
  setOnboarded: (v) => ipcRenderer.invoke('onboarding:set', v),
  onLang: (fn) => ipcRenderer.on('lang', (_e, c) => fn(c)),
  getNarrate: () => ipcRenderer.invoke('narrate:get'),
  setNarrate: (n) => ipcRenderer.invoke('narrate:set', n),
  markPet: (name, on) => ipcRenderer.invoke('pet:mark', { name, on }),
  dismissPet: (n) => ipcRenderer.invoke('pet:dismiss', n),
  setPetName: (name, on) => ipcRenderer.invoke('pets:names', { name, on }),
  onTheme: (fn) => ipcRenderer.on('theme', (_e, t) => fn(t)),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  getTriggers: () => ipcRenderer.invoke('triggers:get'),
  saveTriggers: (defs) => ipcRenderer.invoke('triggers:save', defs),
  defaultTriggers: () => ipcRenderer.invoke('triggers:defaults'),
  testTrigger: (def, line) => ipcRenderer.invoke('triggers:test', { def, line }),
  clearTimers: () => ipcRenderer.invoke('triggers:clearTimers'),
  importTriggers: () => ipcRenderer.invoke('triggers:import'),
  exportTriggers: () => ipcRenderer.invoke('triggers:export'),
  onAlert: (fn) => ipcRenderer.on('alert', (_e, a) => fn(a)),
  detectLogs: () => ipcRenderer.invoke('log:detect'),
  browseLog: () => ipcRenderer.invoke('log:browse'),
  attach: (o) => ipcRenderer.invoke('log:attach', o),
  detach: () => ipcRenderer.invoke('log:detach'),
  openOverlay: () => ipcRenderer.invoke('overlay:open'),
  resetSession: () => ipcRenderer.invoke('session:reset'),
  queryHistory: (q) => ipcRenderer.invoke('history:query', q),
  getFight: (id) => ipcRenderer.invoke('history:fight', id),
  foeList: (sinceMs) => ipcRenderer.invoke('history:foes', sinceMs),
  aggregate: (q) => ipcRenderer.invoke('history:aggregate', q),
  storeStats: () => ipcRenderer.invoke('history:stats'),
  closeOverlay: () => ipcRenderer.invoke('overlay:close'),
  toggleClickThrough: () => ipcRenderer.invoke('overlay:toggleClickThrough'),
  overlayHover: (over) => ipcRenderer.invoke('overlay:hover', over),
  exportEncounter: (enc) => ipcRenderer.invoke('encounter:export', enc),
  reveal: (p) => ipcRenderer.invoke('shell:reveal', p),
  openWiki: (item) => ipcRenderer.invoke('shell:wiki', item),
  wikiItem: (item) => ipcRenderer.invoke('wiki:item', item),
  wikiMob: (name) => ipcRenderer.invoke('wiki:mob', name),
  onSnapshot: (fn) => ipcRenderer.on('snapshot', (_e, s) => fn(s)),
  onOverlayState: (fn) => ipcRenderer.on('overlay:state', (_e, s) => fn(s)),
});
