const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('eql', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setClasses: (list) => ipcRenderer.invoke('classes:set', list),
  setTheme: (t) => ipcRenderer.invoke('theme:set', t),
  setLang: (c) => ipcRenderer.invoke('lang:set', c),
  setOnboarded: (v) => ipcRenderer.invoke('onboarding:set', v),
  onLang: (fn) => ipcRenderer.on('lang', (_e, c) => fn(c)),
  getNarrate: () => ipcRenderer.invoke('narrate:get'),
  setNarrate: (n) => ipcRenderer.invoke('narrate:set', n),
  markPet: (name, on) => ipcRenderer.invoke('pet:mark', { name, on }),
  dismissPet: (n) => ipcRenderer.invoke('pet:dismiss', n),
  setPetName: (name, on) => ipcRenderer.invoke('pets:names', { name, on }),
  setFlag: (key, value) => ipcRenderer.invoke('cfg:flag', { key, value }),
  onTheme: (fn) => ipcRenderer.on('theme', (_e, t) => fn(t)),
  setConfig: (patch) => ipcRenderer.invoke('config:set', patch),
  getTriggers: () => ipcRenderer.invoke('triggers:get'),
  saveTriggers: (defs) => ipcRenderer.invoke('triggers:save', defs),
  defaultTriggers: () => ipcRenderer.invoke('triggers:defaults'),
  testTrigger: (def, line) => ipcRenderer.invoke('triggers:test', { def, line }),
  clearTimers: () => ipcRenderer.invoke('triggers:clearTimers'),
  importTriggers: () => ipcRenderer.invoke('triggers:import'),
  exportTriggers: () => ipcRenderer.invoke('triggers:export'),
  onAlert: (fn) => ipcRenderer.on('alert', (_e, a) => fn(a)),
  detectLogs: () => ipcRenderer.invoke('log:detect'),
  browseLog: () => ipcRenderer.invoke('log:browse'),
  attach: (o) => ipcRenderer.invoke('log:attach', o),
  detach: () => ipcRenderer.invoke('log:detach'),
  openOverlay: () => ipcRenderer.invoke('overlay:open'),
  resetSession: () => ipcRenderer.invoke('session:reset'),
  // La pila de combates del overlay: lo que ya hay, y lo que va cayendo.
  overlayFights: () => ipcRenderer.invoke('overlay:fights'),
  onFightClosed: (fn) => ipcRenderer.on('fight:closed', (_e, f) => fn(f)),
  onSessionCleared: (fn) => ipcRenderer.on('session:cleared', () => fn()),
  queryHistory: (q) => ipcRenderer.invoke('history:query', q),
  getFight: (uid) => ipcRenderer.invoke('history:fight', uid),
  foeList: (sinceMs) => ipcRenderer.invoke('history:foes', sinceMs),
  aggregate: (q) => ipcRenderer.invoke('history:aggregate', q),
  storeStats: () => ipcRenderer.invoke('history:stats'),
  closeOverlay: () => ipcRenderer.invoke('overlay:close'),
  toggleClickThrough: () => ipcRenderer.invoke('overlay:toggleClickThrough'),
  overlayHover: (over) => ipcRenderer.invoke('overlay:hover', over),
  exportEncounter: (enc) => ipcRenderer.invoke('encounter:export', enc),
  reveal: (p) => ipcRenderer.invoke('shell:reveal', p),
  openWiki: (item) => ipcRenderer.invoke('shell:wiki', item),
  wikiItem: (item) => ipcRenderer.invoke('wiki:item', item),
  wikiMob: (name) => ipcRenderer.invoke('wiki:mob', name),
  spellIcons: (names) => ipcRenderer.invoke('wiki:spellIcons', names),
  onSnapshot: (fn) => ipcRenderer.on('snapshot', (_e, s) => fn(s)),
  onOverlayState: (fn) => ipcRenderer.on('overlay:state', (_e, s) => fn(s)),

  // Fusión de mascotas. La interfaz la llamaba sin `?.`, así que el conmutador
  // lanzaba TypeError, no se guardaba la preferencia y el resto del manejador
  // (limpiar las filas y repintar) no llegaba a ejecutarse.
  setMergePets: (v) => ipcRenderer.invoke('pets:merge', v),

  // Aviso de versión nueva. El proceso principal consultaba GitHub y enviaba
  // 'update' desde la 1.0.4, y la interfaz tenía el cartel entero montado,
  // pero por aquí no pasaba el puente: como se llamaban con `?.`, la función
  // llevaba dos versiones muerta sin dar un solo error.
  getUpdate: () => ipcRenderer.invoke('update:get'),
  onUpdate: (fn) => ipcRenderer.on('update', (_e, u) => fn(u)),
  openUpdate: () => ipcRenderer.invoke('update:open'),
  skipUpdate: (v) => ipcRenderer.invoke('update:skip', v),

  // Migración del almacén al formato de la 1.1.0.
  migration: () => ipcRenderer.invoke('store:migration'),
  spellCatalog: (q) => ipcRenderer.invoke('catalog:spells', q),
  setExcluded: (name, on) => ipcRenderer.invoke('excluded:set', { name, on }),
  setCompanion: (name, on) => ipcRenderer.invoke('companions:set', { name, on }),
  setPetOwner: (pet, owner) => ipcRenderer.invoke('pet:owner', { pet, owner }),
  setTrios: (lista) => ipcRenderer.invoke('trios:set', lista),
  trioConflicts: () => ipcRenderer.invoke('trios:conflicts'),
  rebuildStore: () => ipcRenderer.invoke('store:rebuild'),

  // Enciclopedia. Todo sale de la ficha aprendida, que ya está en memoria.
  encZones: () => ipcRenderer.invoke('enc:zones'),
  encZoneFoes: (base, diff) => ipcRenderer.invoke('enc:zoneFoes', { base, diff }),
  encFoe: (name) => ipcRenderer.invoke('enc:foe', name),
  encFoeAt: (name, diff) => ipcRenderer.invoke('enc:foeAt', { name, diff }),
  encFoes: () => ipcRenderer.invoke('enc:foes'),
  encLoot: () => ipcRenderer.invoke('enc:loot'),
  encDeaths: () => ipcRenderer.invoke('enc:deaths'),
  encProgress: () => ipcRenderer.invoke('enc:progress'),
  encFights: (q) => ipcRenderer.invoke('enc:fights', q),
  encCounts: () => ipcRenderer.invoke('enc:counts'),
  encStatus: () => ipcRenderer.invoke('enc:status'),
  encRebuild: () => ipcRenderer.invoke('enc:rebuild'),
});
