/**
 * QUÉ CLASE DEMUESTRA CADA ACCIÓN.
 *
 * En EQL puedes cambiar de trío de clases y **el registro no lo notifica en
 * ningún sitio**. Lo único que lo cuenta es el /who, y nadie lo escribe cada
 * media hora: medido en un registro real de 27 horas, cinco /who en total, y
 * entre el cambio de trío y el /who que lo confirmó pasaron dos horas y cuarto
 * —32 peleas guardadas con el trío y el nivel equivocados—.
 *
 * La señal continua es qué HACES tú. Pero sólo prueba algo lo que sea
 * EXCLUSIVO de una clase: si dos clases tienen lo mismo, hacerlo no dice cuál
 * llevas.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * POR QUÉ ESTÁN LAS DOCE Y NO LAS QUE SE JUEGAN
 *
 * LA EXCLUSIVIDAD NO SE PUEDE CALCULAR CON LISTAS PARCIALES. Un hechizo parece
 * exclusivo en cuanto falta la lista de quien también lo tiene, y eso no es una
 * laguna: es una AFIRMACIÓN FALSA, porque el programa lo usa para decidir un
 * trío. Aquí había cinco listas —SHD, MAG, DRU, SHM, WIZ— y faltaba
 * Necromancer, que comparte con Shadow Knight casi todo su libro.
 *
 * MEDIDO AL TRAER LAS DOCE, sobre las 459 pruebas que este fichero afirmaba:
 *
 *     309  seguían en pie
 *     135  ERAN FALSAS  (SHD 44, SHM 43, DRU 35, MAG 13)
 *      15  no aparecen en ninguna lista de la wiki: no se puede afirmar nada
 *
 * Y sobre los 9.026 lanzamientos de un registro real, el 67,8% se estaba
 * usando como prueba de una clase que no demuestran. Sólo `Drain Spirit`
 * —NEC/SHD, no SHD— son 3.896.
 *
 * Por eso este fichero guarda HECHIZO -> CLASES, y no CLASE -> HECHIZOS. La
 * exclusividad deja de ser algo que se deduce de lo que hay y pasa a ser algo
 * que está escrito: si un hechizo tiene dos códigos, no prueba nada, y se ve
 * de un vistazo sin cruzar doce listas.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * PROCEDENCIA: CONSULTADO. NO ES MEDIDO Y NO DEBE PARECERLO.
 *
 * Origen:     eqlwiki.com, páginas de clase (/Bard … /Wizard)
 * Consultado: 2026-08-10
 * Extracción: la línea de clases que cada ficha de hechizo trae dentro
 *             (`spell-examine-classline`: «SHD(49)», «DRU(9)/RNG(22)»), que
 *             es la wiki declarando la exclusividad, no nosotros deduciéndola.
 * Rangos:     normalizados con `baseSpell()` — la wiki los lista sueltos
 *             (Drain Spirit I…X) y aquí interesa la base.
 * Volumen:    1.492 fichas leídas → 1037 hechizos base, 798 exclusivos.
 *
 *   BRD  Bard             60 hechizos,   60 exclusivos
 *   BST  Beastlord        76 hechizos,   27 exclusivos
 *   CLR  Cleric          160 hechizos,   61 exclusivos
 *   DRU  Druid           189 hechizos,  101 exclusivos
 *   ENC  Enchanter       187 hechizos,  143 exclusivos
 *   MAG  Magician        155 hechizos,  123 exclusivos
 *   NEC  Necromancer     143 hechizos,   62 exclusivos
 *   PAL  Paladin          70 hechizos,   12 exclusivos
 *   RNG  Ranger           66 hechizos,   14 exclusivos
 *   SHD  Shadow Knight    64 hechizos,   17 exclusivos
 *   SHM  Shaman          163 hechizos,   72 exclusivos
 *   WIZ  Wizard          140 hechizos,  106 exclusivos
 *
 * SI EQL CAMBIA LISTAS EN UN PARCHE, esa fecha es lo que permite saber que hay
 * que volver a bajarlas. Nada de aquí se ha comprobado contra el juego.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * LO QUE ESTO NO CUBRE, Y HAY QUE SABERLO
 *
 * Las clases que no lanzan hechizos NO SALEN NUNCA en una lista de hechizos:
 * Warrior, Monk y Rogue no tienen ni una entrada aquí y se pueden jugar igual.
 * De ésas el rastro son ACCIONES —golpes exclusivos, disciplinas, posturas— y
 * por eso esta función se llama `proofOf(accion)` y no `proofOfSpell`: lo que
 * entra por aquí no tiene por qué ser un hechizo. Ver `ACCIONES`.
 */
import { baseSpell } from './spells.js';

/** Códigos de las doce clases lanzadoras, más las tres que no lanzan. */
export const CLASES_CONOCIDAS = ['BRD', 'BST', 'CLR', 'DRU', 'ENC', 'MAG', 'NEC', 'PAL', 'RNG', 'SHD', 'SHM', 'WIZ'];
export const CLASES_SIN_HECHIZOS = ['WAR', 'MNK', 'ROG'];

/**
 * hechizo base -> clases que lo tienen, separadas por «/».
 *
 * Generado, no escrito a mano. Para rehacerlo hay que volver a bajar las doce
 * páginas y actualizar la fecha de arriba; editar una línea suelta aquí deja el
 * fichero diciendo que se consultó un día en que no se consultó.
 */
const HECHIZOS = {
  "Aanya's Animation": 'ENC',
  "Abolish Disease": 'SHM',
  "Abolish Poison": 'CLR',
  "Abundant Drink": 'CLR',
  "Abundant Food": 'CLR',
  "Adorning Grace": 'ENC',
  "Affliction": 'SHM',
  "Agility": 'SHM',
  "Agilmente's Aria of Eagles": 'BRD',
  "Alacrity": 'ENC/SHM',
  "Alenia's Disenchanting Melody": 'BRD',
  "Alliance": 'ENC',
  "Allure": 'ENC',
  "Allure of Death": 'NEC',
  "Allure of the Wild": 'DRU',
  "Alluring Aura": 'SHM',
  "Alter Plane: Hate": 'WIZ',
  "Alter Plane: Sky": 'WIZ',
  "Amplification": 'BRD',
  "Anarchy": 'ENC',
  "Angstlich's Appalling Screech": 'BRD',
  "Animate Dead": 'NEC/SHD',
  "Anthem De Arms": 'BRD',
  "Arch Shielding": 'ENC/MAG/NEC/WIZ',
  "Aria of Asceticism": 'BRD',
  "Armor of Faith": 'CLR/PAL',
  "Armor of Protection": 'CLR',
  "Armor of the Faithful": 'CLR',
  "Assiduous Vision": 'SHM',
  "Asystole": 'NEC',
  "Atone": 'CLR',
  "Augment Death": 'NEC',
  "Augmentation": 'ENC',
  "Auspice": 'NEC',
  "Avalanche": 'DRU',
  "Banish Summoned": 'DRU/MAG',
  "Banish Undead": 'CLR/NEC',
  "Banshee Aura": 'NEC',
  "Barbcoat": 'DRU/RNG',
  "Barrier of Combustion": 'MAG',
  "Befriend Animal": 'DRU/SHM',
  "Beguile": 'ENC',
  "Beguile Animals": 'DRU',
  "Beguile Plants": 'DRU',
  "Beguile Undead": 'NEC',
  "Benevolence": 'ENC',
  "Berserker Spirit": 'ENC',
  "Berserker Strength": 'ENC',
  "Bind Affinity": 'CLR/DRU/ENC/MAG/NEC/SHM/WIZ',
  "Bind Sight": 'ENC/RNG/WIZ',
  "Blanket of Forgetfulness": 'ENC',
  "Blast of Frost": 'BST',
  "Blast of Poison": 'SHM',
  "Blaze": 'MAG',
  "Blessing of Faith": 'CLR',
  "Blessing of Piety": 'CLR',
  "Blessing of the Knight": 'CLR',
  "Blessing of the Lord Commander": 'CLR',
  "Blessing of the Page": 'CLR',
  "Blessing of the Squire": 'CLR',
  "Blinding Luminance": 'CLR/SHM',
  "Blizzard Blast": 'SHM',
  "Blood of Pain": 'SHD',
  "Blooming Heal": 'DRU',
  "Blossoming Heal": 'DRU',
  "Boil Blood": 'NEC',
  "Bolt of Flame": 'MAG',
  "Boltran's Animation": 'ENC',
  "Bond of Death": 'NEC',
  "Bonds of Force": 'WIZ',
  "Bone Walk": 'NEC/SHD',
  "Boon of the Clear Mind": 'ENC',
  "Boon of the Garou": 'ENC',
  "Bounce": 'ENC/MAG/NEC/WIZ',
  "Bramblecoat": 'DRU/RNG',
  "Bravery": 'CLR',
  "Breath of the Dead": 'NEC/SHD',
  "Breeze": 'ENC',
  "Brell's Steadfast Aegis": 'PAL',
  "Brilliance": 'ENC',
  "Brusco's Boastful Bellow": 'BRD',
  "Budding Heal": 'DRU',
  "Burn": 'MAG',
  "Burning Arrow": 'RNG',
  "Burnout": 'MAG',
  "Burst of Fire": 'DRU/RNG',
  "Burst of Flame": 'DRU/MAG/SHM',
  "Burst of Strength": 'SHM',
  "Cackling Bones": 'NEC',
  "Cajole Undead": 'NEC',
  "Cajoling Whispers": 'ENC',
  "Call of Bones": 'NEC',
  "Call of Earth": 'RNG',
  "Call of Flame": 'RNG',
  "Call of Sky": 'RNG',
  "Calm": 'CLR/ENC/PAL',
  "Calm Animal": 'DRU/RNG',
  "Calming Visage": 'ENC',
  "Camouflage": 'DRU/RNG',
  "Cancel Magic": 'BST/CLR/DRU/ENC/MAG/NEC/PAL/RNG/SHD/SHM/WIZ',
  "Cancelling of Life": 'NEC/SHD',
  "Cannibalize": 'SHM',
  "Cantana of Soothing": 'BRD',
  "Careless Lightning": 'DRU/RNG',
  "Cascade of Hail": 'DRU',
  "Cascading Darkness": 'NEC',
  "Cassindra's Chant of Clarity": 'BRD',
  "Cassindra's Chorus of Clarity": 'BRD',
  "Cassindra's Elegy": 'BRD',
  "Cast Force": 'WIZ',
  "Cast Sight": 'ENC',
  "Cavorting Bones": 'NEC',
  "Cazic Temple Gate": 'WIZ',
  "Cazic Temple Portal": 'WIZ',
  "Cease": 'PAL',
  "Celerity": 'ENC',
  "Celestial Echo": 'CLR',
  "Celestial Healing": 'CLR',
  "Celestial Health": 'CLR',
  "Celestial Remedy": 'CLR',
  "Center": 'CLR/PAL',
  "Cessation of Life": 'NEC',
  "Chant of Battle": 'BRD',
  "Chaos Flux": 'ENC',
  "Chaotic Feedback": 'ENC',
  "Charisma": 'SHM',
  "Charm": 'ENC',
  "Charm Animals": 'DRU/SHM',
  "Chase the Moon": 'ENC',
  "Chill Sight": 'WIZ',
  "Chilling Embrace": 'NEC',
  "Chloroplast": 'DRU/SHM',
  "Choke": 'ENC',
  "Chords of Dissonance": 'BRD',
  "Cinda's Charismatic Carillon": 'BRD',
  "Cinder Bolt": 'MAG',
  "Circle of Feerrott": 'DRU',
  "Circle of Force": 'WIZ',
  "Circle of Karana": 'DRU',
  "Circle of Lavastorm": 'DRU',
  "Circle of Misty Thicket": 'DRU',
  "Circle of South Ro": 'DRU',
  "Circle of Steamfont": 'DRU',
  "Circle of Stonebrunt": 'DRU',
  "Circle of Surefall Glade": 'DRU',
  "Circle of Toxxulia": 'DRU',
  "Circle of West Commons": 'DRU',
  "Clarify Mana": 'ENC',
  "Clarity": 'ENC',
  "Clinging Darkness": 'NEC/SHD',
  "Cloud": 'ENC',
  "Coldlight": 'NEC',
  "Collaboration": 'ENC',
  "Color Flux": 'ENC',
  "Color Shift": 'ENC',
  "Color Skew": 'ENC',
  "Column of Fire": 'MAG',
  "Column of Frost": 'WIZ',
  "Column of Lightning": 'WIZ',
  "Combust": 'DRU',
  "Companion Spirit": 'SHM',
  "Concussion": 'WIZ',
  "Conflagration": 'WIZ',
  "Conjuration: Air": 'MAG',
  "Conjuration: Earth": 'MAG',
  "Conjuration: Fire": 'MAG',
  "Conjuration: Water": 'MAG',
  "Convoke Shadow": 'NEC/SHD',
  "Cornucopia": 'MAG',
  "Corporeal Empathy": 'NEC',
  "Counteract Disease": 'BST/CLR/DRU/NEC/SHM',
  "Counteract Poison": 'CLR/DRU/PAL/SHM',
  "Courage": 'CLR/PAL',
  "Covetous Subversion": 'NEC',
  "Creeping Crud": 'DRU',
  "Creeping Vision": 'SHM',
  "Crission's Pixie Strike": 'BRD',
  "Crystallize Mana": 'ENC',
  "Cure Blindness": 'CLR/SHM',
  "Cure Disease": 'BST/CLR/DRU/NEC/PAL/RNG/SHM',
  "Cure Poison": 'BST/CLR/DRU/PAL/RNG/SHM',
  "Curse": 'SHM',
  "Curse of the Simple Mind": 'ENC',
  "Dagger of Symbols": 'MAG',
  "Dance of the Fireflies": 'DRU/RNG',
  "Daring": 'CLR/PAL',
  "Dark Empathy": 'NEC/SHD',
  "Dark Pact": 'NEC',
  "Dark Soul": 'NEC',
  "Dark Temptation": 'SHD',
  "Dazzle": 'ENC',
  "Dead Man Floating": 'NEC',
  "Dead Men Floating": 'NEC',
  "Deadeye": 'NEC',
  "Deftness": 'SHM',
  "Denon's Desperate Dirge": 'BRD',
  "Denon's Disruptive Discord": 'BRD',
  "Denon's Dissension": 'BRD',
  "Desist": 'PAL',
  "Despair": 'SHD',
  "Dexterity": 'SHM',
  "Dexterous Aura": 'SHM',
  "Diamondskin": 'NEC/WIZ',
  "Dimensional Hole": 'MAG',
  "Dimensional Pocket": 'MAG',
  "Discordant Mind": 'ENC',
  "Disease Cloud": 'NEC/SHD',
  "Disempower": 'ENC/SHM',
  "Dismiss Summoned": 'CLR/DRU/MAG/RNG',
  "Dismiss Undead": 'CLR/NEC/PAL/SHD',
  "Distill Mana": 'ENC',
  "Divine Aura": 'CLR/PAL',
  "Divine Barrier": 'CLR',
  "Divine Might": 'PAL',
  "Divine Purpose": 'PAL',
  "Divine Vigor": 'PAL',
  "Dizzying Wind": 'DRU',
  "Dominate Undead": 'NEC',
  "Dooming Darkness": 'NEC/SHD',
  "Drain Soul": 'NEC',
  "Drain Spirit": 'NEC/SHD',
  "Drifting Death": 'DRU',
  "Drones of Doom": 'DRU',
  "Drowsy": 'BST/SHM',
  "Dustdevil": 'DRU',
  "Dyn's Dizzying Draught": 'ENC',
  "Earthquake": 'CLR/DRU',
  "Ebbing Strength": 'ENC',
  "Echo of Health": 'CLR',
  "Echoing Light": 'CLR',
  "Efflorescing Heal": 'DRU',
  "Elemental Armor": 'MAG/WIZ',
  "Elemental Maelstrom": 'MAG',
  "Elemental Rhythms": 'BRD',
  "Elemental Shield": 'MAG/WIZ',
  "Elemental: Air": 'MAG',
  "Elemental: Earth": 'MAG',
  "Elemental: Fire": 'MAG',
  "Elemental: Water": 'MAG',
  "Elementaling: Air": 'MAG',
  "Elementaling: Earth": 'MAG',
  "Elementaling: Fire": 'MAG',
  "Elementaling: Water": 'MAG',
  "Elementalkin: Air": 'MAG',
  "Elementalkin: Earth": 'MAG',
  "Elementalkin: Fire": 'MAG',
  "Elementalkin: Water": 'MAG',
  "Elnerick's Entombment of Ice": 'WIZ',
  "Enchant Clay": 'ENC',
  "Enchant Electrum": 'ENC',
  "Enchant Gold": 'ENC',
  "Enchant Platinum": 'ENC',
  "Enchant Silver": 'ENC',
  "Endure Cold": 'BST/CLR/DRU/NEC/RNG/SHD/SHM',
  "Endure Disease": 'BST/CLR/DRU/NEC/PAL/SHD/SHM',
  "Endure Fire": 'BST/CLR/DRU/RNG/SHM',
  "Endure Magic": 'BST/CLR/DRU/ENC/PAL/SHM',
  "Endure Poison": 'BST/CLR/DRU/PAL/SHM',
  "Enduring Breath": 'BST/DRU/ENC/RNG/SHM',
  "Energy Storm": 'WIZ',
  "Enfeeblement": 'ENC',
  "Engulfing Darkness": 'NEC/SHD',
  "Engulfing Roots": 'DRU',
  "Ensnare": 'DRU',
  "Ensnaring Roots": 'DRU/RNG',
  "Enthrall": 'ENC',
  "Enticement of Flame": 'WIZ',
  "Entrance": 'ENC',
  "Entrancing Lights": 'ENC',
  "Enveloping Roots": 'DRU',
  "Envenomed Bolt": 'NEC/SHM',
  "Envenomed Breath": 'BST/SHM',
  "Eternities Torment": 'NEC',
  "Ethereal Cleansing": 'PAL',
  "Evacuate: Greater Faydark": 'WIZ',
  "Evacuate: Greater Nektulos": 'WIZ',
  "Evacuate: North Karana": 'WIZ',
  "Evacuate: South Ro": 'WIZ',
  "Evacuate: West Karana": 'WIZ',
  "Everfount": 'MAG',
  "Everlasting Breath": 'DRU',
  "Expedience": 'MAG',
  "Expel Summoned": 'CLR/DRU/MAG',
  "Expel Undead": 'CLR/NEC',
  "Expulse Summoned": 'CLR/DRU/MAG',
  "Expulse Undead": 'CLR/NEC/PAL/SHD',
  "Eye of Confusion": 'ENC',
  "Eye of Zomm": 'MAG/WIZ',
  "Eyes of the Cat": 'RNG',
  "Fade": 'WIZ',
  "Fear": 'CLR/ENC/NEC/SHD',
  "Feckless Might": 'ENC',
  "Feedback": 'ENC',
  "Feet like Cat": 'RNG/SHM',
  "Feign Death": 'NEC/SHD',
  "Feral Spirit": 'DRU',
  "Fingers of Fire": 'WIZ',
  "Fire": 'DRU',
  "Fire Bolt": 'WIZ',
  "Fire Flux": 'MAG',
  "Fire Spiral of Al'Kabor": 'WIZ',
  "Firefist": 'DRU/RNG',
  "Firestorm": 'WIZ',
  "Firestrike": 'DRU',
  "Fixation of Ro": 'DRU',
  "Flame Arc": 'MAG',
  "Flame Bolt": 'MAG',
  "Flame Flux": 'MAG',
  "Flame Lick": 'DRU/RNG',
  "Flame of Light": 'PAL',
  "Flame Shock": 'WIZ',
  "Flaming Arrow": 'RNG',
  "Flare": 'MAG',
  "Flash of Light": 'BST/CLR/PAL/SHM',
  "Fleeting Fury": 'BST/SHM',
  "Flowering Heal": 'DRU',
  "Focus Death": 'NEC',
  "Force": 'CLR',
  "Force of Nature": 'RNG',
  "Force Snap": 'WIZ',
  "Force Spiral of Al'Kabor": 'WIZ',
  "Force Strike": 'WIZ',
  "Forest's Renewal": 'DRU',
  "Form of Bleached Bone": 'NEC',
  "Form of Chilled Bone": 'NEC',
  "Form of the Bear": 'SHM',
  "Form of the Great Wolf": 'DRU',
  "Frenzied Spirit": 'SHM',
  "Frenzied Strength": 'CLR',
  "Frenzy": 'BST/SHM',
  "Frost Bolt": 'WIZ',
  "Frost Dagger": 'BST',
  "Frost Rift": 'SHM',
  "Frost Shard": 'BST',
  "Frost Shock": 'WIZ',
  "Frost Spiral of Al'Kabor": 'WIZ',
  "Frost Storm": 'WIZ',
  "Frost Strike": 'SHM',
  "Fufil's Curtailing Chant": 'BRD',
  "Furious Strength": 'SHM',
  "Furor": 'CLR/PAL',
  "Fury": 'SHM',
  "Fury of Air": 'DRU',
  "Gale of Poison": 'SHM',
  "Garrison's Mighty Mana Shock": 'WIZ',
  "Gasping Embrace": 'ENC',
  "Gate": 'CLR/DRU/ENC/MAG/NEC/SHM/WIZ',
  "Gather Shadows": 'NEC/SHD',
  "Gaze": 'WIZ',
  "Gift of Magic": 'ENC',
  "Glamour": 'SHM',
  "Glimpse": 'RNG/WIZ',
  "Grasping Roots": 'DRU/RNG',
  "Gravity Flux": 'ENC/WIZ',
  "Greater Conjuration: Air": 'MAG',
  "Greater Conjuration: Earth": 'MAG',
  "Greater Conjuration: Fire": 'MAG',
  "Greater Conjuration: Water": 'MAG',
  "Greater Faydark Gate": 'WIZ',
  "Greater Faydark Portal": 'WIZ',
  "Greater Healing": 'BST/CLR/DRU/PAL/RNG/SHM',
  "Greater Mass Imbue Fire Opal": 'WIZ',
  "Greater Shielding": 'ENC/MAG/NEC/WIZ',
  "Greater Summoning: Air": 'MAG',
  "Greater Summoning: Earth": 'MAG',
  "Greater Summoning: Fire": 'MAG',
  "Greater Summoning: Water": 'MAG',
  "Greater Wolf Form": 'DRU',
  "Grim Aura": 'NEC/SHD',
  "Group Resist Magic": 'ENC',
  "Grow": 'SHM',
  "Guard": 'CLR/PAL',
  "Guard of Alendar": 'ENC',
  "Guard of Vie": 'CLR',
  "Guardian": 'SHM',
  "Guardian Rhythms": 'BRD',
  "Guardian Spirit": 'SHM',
  "Halo of Light": 'CLR/DRU/PAL/WIZ',
  "Hammer of Requital": 'CLR',
  "Hammer of Striking": 'CLR/PAL',
  "Hammer of Wrath": 'CLR/PAL',
  "Harmony": 'DRU/RNG',
  "Harmony of Nature": 'DRU/RNG',
  "Harmshield": 'NEC/SHD',
  "Harnessing of Spirit": 'SHM',
  "Harvest": 'WIZ',
  "Haunting Corpse": 'NEC',
  "Haunting Visage": 'ENC',
  "Hawk Eye": 'RNG',
  "Haze": 'ENC',
  "Healing": 'BST/CLR/DRU/PAL/RNG/SHM',
  "Healing Light": 'CLR',
  "Health": 'SHM',
  "Heart Flutter": 'NEC/SHD',
  "Heat Blood": 'NEC/SHD',
  "Heat Sight": 'WIZ',
  "Herikol's Soothing": 'BST',
  "Holy Armor": 'CLR/PAL',
  "Holy Might": 'CLR/PAL',
  "Hungry Earth": 'NEC',
  "Hymn of Restoration": 'BRD',
  "Ice": 'DRU',
  "Ice Comet": 'WIZ',
  "Ice Shock": 'WIZ',
  "Ice Spear": 'BST',
  "Icestrike": 'WIZ',
  "Ignite": 'DRU/RNG',
  "Ignite Blood": 'NEC',
  "Ignite Bones": 'NEC',
  "Illusion: Air Elemental": 'ENC',
  "Illusion: Barbarian": 'ENC',
  "Illusion: Dark Elf": 'ENC',
  "Illusion: Dry Bone": 'ENC',
  "Illusion: Dwarf": 'ENC',
  "Illusion: Earth Elemental": 'ENC',
  "Illusion: Erudite": 'ENC',
  "Illusion: Fire Elemental": 'ENC',
  "Illusion: Gnome": 'ENC',
  "Illusion: Half Elf": 'ENC',
  "Illusion: Halfling": 'ENC',
  "Illusion: High Elf": 'ENC',
  "Illusion: Human": 'ENC',
  "Illusion: Iksar": 'ENC',
  "Illusion: Ogre": 'ENC',
  "Illusion: Scaled Wolf": 'ENC',
  "Illusion: Skeleton": 'ENC',
  "Illusion: Spirit Wolf": 'ENC',
  "Illusion: Tree": 'ENC',
  "Illusion: Troll": 'ENC',
  "Illusion: Water Elemental": 'ENC',
  "Illusion: Werewolf": 'ENC',
  "Illusion: Wood Elf": 'ENC',
  "Imbue Amber": 'CLR/SHM',
  "Imbue Black Pearl": 'CLR',
  "Imbue Black Sapphire": 'CLR',
  "Imbue Diamond": 'CLR/SHM',
  "Imbue Emerald": 'CLR/DRU',
  "Imbue Fire Opal": 'WIZ',
  "Imbue Ivory": 'SHM',
  "Imbue Jade": 'SHM',
  "Imbue Opal": 'CLR',
  "Imbue Peridot": 'CLR',
  "Imbue Plains Pebble": 'CLR/DRU',
  "Imbue Rose Quartz": 'CLR',
  "Imbue Ruby": 'CLR',
  "Imbue Sapphire": 'CLR/SHM',
  "Imbue Topaz": 'CLR',
  "Immobilize": 'CLR/ENC/WIZ',
  "Immolate": 'DRU/RNG',
  "Impart Strength": 'NEC',
  "Impassivity": 'SHM',
  "Improved Invisibility": 'ENC',
  "Improved Invisibility to Undead": 'CLR/NEC',
  "Improved Superior Camo": 'DRU',
  "Incapacitate": 'ENC/SHM',
  "Incinerate Bones": 'NEC',
  "Infectious Cloud": 'NEC/SHM',
  "Inferno Shield": 'MAG',
  "Inferno Shock": 'WIZ',
  "Infusion of Spirit": 'SHM',
  "Inner Fire": 'BST/SHM',
  "Insidious Fever": 'SHM',
  "Insidious Malady": 'SHM',
  "Insidious Retrogression": 'NEC',
  "Insight": 'ENC',
  "Insipid Weakness": 'ENC',
  "Inspire Fear": 'CLR',
  "Instill": 'CLR/ENC/SHM/WIZ',
  "Instrument of Nife": 'PAL',
  "Intellectual Advancement": 'ENC',
  "Intellectual Superiority": 'ENC',
  "Intensify Death": 'NEC',
  "Invisibility": 'BST/ENC/MAG/SHM/WIZ',
  "Invisibility to Undead": 'WIZ',
  "Invisibility versus Animals": 'DRU/SHM',
  "Invisibility versus Undead": 'CLR/ENC/NEC/PAL',
  "Invoke Death": 'NEC',
  "Invoke Fear": 'CLR/ENC/NEC/SHD',
  "Invoke Lightning": 'DRU/RNG',
  "Invoke Shadow": 'NEC',
  "Jaxan's Jig o' Vigor": 'BRD',
  "Jolt": 'RNG',
  "Jonthan's Provocation": 'BRD',
  "Jonthan's Whistling Warsong": 'BRD',
  "Juli's Animation": 'ENC',
  "Kelin's Lucid Lullaby": 'BRD',
  "Kelin's Lugubrious Lament": 'BRD',
  "Keshuval's Rejuvenation": 'BST',
  "Kilan's Animation": 'ENC',
  "Kintaz's Animation": 'ENC',
  "Kragg's Salve": 'SHM',
  "Languid Pace": 'BST/ENC',
  "Largo's Melodic Binding": 'BRD',
  "Lava Bolt": 'MAG',
  "Lava Storm": 'WIZ',
  "Leach": 'NEC',
  "Leatherskin": 'NEC/WIZ',
  "Leering Corpse": 'NEC/SHD',
  "Legacy of Spike": 'DRU',
  "Lesser Conjuration: Air": 'MAG',
  "Lesser Conjuration: Earth": 'MAG',
  "Lesser Conjuration: Fire": 'MAG',
  "Lesser Conjuration: Water": 'MAG',
  "Lesser Evacuate": 'WIZ',
  "Lesser Familiar": 'WIZ',
  "Lesser Shielding": 'ENC/MAG/NEC/WIZ',
  "Lesser Succor": 'DRU',
  "Lesser Summoning: Air": 'MAG',
  "Lesser Summoning: Earth": 'MAG',
  "Lesser Summoning: Fire": 'MAG',
  "Lesser Summoning: Water": 'MAG',
  "Leviathan Eyes": 'ENC',
  "Levitate": 'BST/DRU/ENC/RNG/SHM/WIZ',
  "Levitation": 'DRU/WIZ',
  "Lich": 'NEC',
  "Lifedraw": 'NEC/SHD',
  "Lifespike": 'NEC/SHD',
  "Lifetap": 'NEC/SHD',
  "Light Healing": 'BST/CLR/DRU/PAL/RNG/SHM',
  "Lightning Blast": 'DRU',
  "Lightning Bolt": 'WIZ',
  "Lightning Shock": 'WIZ',
  "Lightning Storm": 'WIZ',
  "Lightning Strike": 'DRU',
  "Listless Power": 'BST/ENC/SHM',
  "Lull": 'CLR/ENC/PAL',
  "Lull Animal": 'DRU/RNG',
  "Lyssa's Solidarity of Vision": 'BRD',
  "Lyssa's Veracious Concord": 'BRD',
  "Magical Monologue": 'BRD',
  "Magnify": 'WIZ',
  "Major Shielding": 'ENC/MAG/NEC/WIZ',
  "Malaise": 'MAG/SHM',
  "Malaria": 'BST',
  "Malignant Dead": 'NEC',
  "Malisement": 'MAG/SHM',
  "Malosi": 'SHM',
  "Mana Detonation": 'WIZ',
  "Mana Ignition": 'WIZ',
  "Mana Sieve": 'ENC',
  "Markar`s Clash": 'WIZ',
  "Mass Clarify Mana": 'ENC',
  "Mass Crystallize Mana": 'ENC',
  "Mass Distill Mana": 'ENC',
  "Mass Enchant Clay": 'ENC',
  "Mass Enchant Electrum": 'ENC',
  "Mass Enchant Gold": 'ENC',
  "Mass Enchant Platinum": 'ENC',
  "Mass Enchant Silver": 'ENC',
  "Mass Imbue Amber": 'CLR/SHM',
  "Mass Imbue Black Pearl": 'CLR',
  "Mass Imbue Black Sapphire": 'CLR',
  "Mass Imbue Diamond": 'CLR/SHM',
  "Mass Imbue Fire Opal": 'WIZ',
  "Mass Imbue Ivory": 'SHM',
  "Mass Imbue Jade": 'SHM',
  "Mass Imbue Opal": 'CLR',
  "Mass Imbue Peridot": 'CLR',
  "Mass Imbue Plains Pebble": 'CLR/DRU',
  "Mass Imbue Rose Quartz": 'CLR',
  "Mass Imbue Ruby": 'CLR',
  "Mass Imbue Sapphire": 'CLR/SHM',
  "Mass Imbue Topaz": 'CLR',
  "Mass Purify Mana": 'ENC',
  "Mass Thicken Mana": 'ENC',
  "McVaxius' Berserker Crescendo": 'BRD',
  "Melanie's Mellifluous Motion": 'BRD',
  "Memory Blur": 'ENC',
  "Mend Bones": 'NEC',
  "Mesmerization": 'ENC',
  "Mesmerize": 'ENC',
  "Mind Wipe": 'ENC',
  "Minor Conjuration: Air": 'MAG',
  "Minor Conjuration: Earth": 'MAG',
  "Minor Conjuration: Fire": 'MAG',
  "Minor Conjuration: Water": 'MAG',
  "Minor Familiar": 'WIZ',
  "Minor Healing": 'BST/CLR/DRU/PAL/RNG/SHM',
  "Minor Illusion": 'ENC',
  "Minor Shielding": 'ENC/MAG/NEC/WIZ',
  "Minor Summoning: Air": 'MAG',
  "Minor Summoning: Earth": 'MAG',
  "Minor Summoning: Fire": 'MAG',
  "Minor Summoning: Water": 'MAG',
  "Mircyl's Animation": 'ENC',
  "Mist": 'ENC',
  "Modulating Rod": 'MAG',
  "Monster Summoning": 'MAG',
  "Nature's Precision": 'RNG',
  "Nature's Renewal": 'DRU',
  "Negation of Life": 'NEC/SHD',
  "Nektulos Gate": 'WIZ',
  "Nektulos Portal": 'WIZ',
  "Nimble": 'SHM',
  "Niv's Melody of Preservation": 'BRD',
  "Nonchalance": 'SHM',
  "North Karana Gate": 'WIZ',
  "North Karana Portal": 'WIZ',
  "North Ro Gate": 'WIZ',
  "North Ro Portal": 'WIZ',
  "Nullify Magic": 'CLR/DRU/ENC/MAG/NEC/SHM/WIZ',
  "Numb the Dead": 'NEC/SHD',
  "Numbing Cold": 'WIZ',
  "O'Keils Radiation": 'WIZ',
  "O`Keil's Embers": 'WIZ',
  "O`Keil's Flickering Flame": 'WIZ',
  "O`Keil's Levity": 'WIZ',
  "Obscure": 'ENC',
  "Odium": 'SHM',
  "Pacify": 'CLR/ENC/PAL',
  "Pack Chloroplast": 'DRU',
  "Pack Regeneration": 'DRU',
  "Pack Shrew": 'BST/DRU/RNG/SHM',
  "Pack Spirit": 'DRU',
  "Pact of Shadow": 'NEC',
  "Panic Animal": 'DRU/RNG',
  "Panic the Dead": 'CLR/NEC',
  "Paralyzing Earth": 'ENC/NEC/WIZ',
  "Pendril's Animation": 'ENC',
  "Phantom Chain": 'MAG',
  "Phantom Leather": 'MAG',
  "Phantom Plate": 'MAG',
  "Pillage Enchantment": 'ENC',
  "Pillar of Fire": 'WIZ',
  "Plague": 'SHM',
  "Pogonip": 'DRU',
  "Poison Bolt": 'NEC',
  "Poison Storm": 'SHM',
  "Primal Remedy": 'MAG',
  "Project Lightning": 'WIZ',
  "Promised Renewal": 'CLR',
  "Protect": 'BST/SHM',
  "Protection of Diamond": 'DRU',
  "Protection of Nature": 'DRU',
  "Protection of Rock": 'DRU',
  "Protection of Steel": 'DRU',
  "Protection of Wood": 'DRU',
  "Psalm of Cooling": 'BRD',
  "Psalm of Mystic Shielding": 'BRD',
  "Psalm of Purity": 'BRD',
  "Psalm of Vitality": 'BRD',
  "Psalm of Warmth": 'BRD',
  "Purify Mana": 'ENC',
  "Purifying Rhythms": 'BRD',
  "Quickness": 'ENC/SHM',
  "Radiant Visage": 'ENC',
  "Rage": 'SHM',
  "Raging Strength": 'BST/SHM',
  "Rain of Blades": 'MAG',
  "Rain of Fire": 'MAG',
  "Rain of Lava": 'MAG',
  "Rain of Spikes": 'MAG',
  "Rain of Swords": 'MAG',
  "Rampage": 'ENC',
  "Rapacious Subvention": 'NEC',
  "Reanimation": 'CLR/PAL',
  "Reckless Strength": 'CLR/PAL',
  "Reclaim Energy": 'ENC/MAG/NEC',
  "Reconstitution": 'CLR/PAL',
  "Refresh Summoning": 'MAG',
  "Regeneration": 'DRU/SHM',
  "Remove Curse": 'CLR/DRU/PAL/SHM',
  "Remove Lesser Curse": 'CLR/DRU/PAL/SHM',
  "Remove Minor Curse": 'CLR/DRU/PAL/SHM',
  "Rend": 'WIZ',
  "Renew Bones": 'NEC',
  "Renew Elements": 'MAG',
  "Renew Summoning": 'MAG',
  "Renewal": 'CLR/PAL',
  "Renewing Echo": 'CLR',
  "Reoccurring Amnesia": 'ENC',
  "Reparation": 'CLR/PAL',
  "Resist Cold": 'CLR/DRU/NEC/SHD/SHM',
  "Resist Disease": 'CLR/DRU/NEC/PAL/SHM',
  "Resist Fire": 'CLR/DRU/RNG/SHM',
  "Resist Magic": 'CLR/DRU/ENC/SHM',
  "Resist Poison": 'CLR/DRU/SHM',
  "Resistant Skin": 'WIZ',
  "Resolution": 'CLR',
  "Rest the Dead": 'NEC',
  "Restless Bones": 'NEC/SHD',
  "Restoration": 'CLR',
  "Resurrection": 'CLR',
  "Resuscitate": 'CLR',
  "Retribution": 'CLR/PAL',
  "Revive": 'CLR/PAL',
  "Riftwind's Protection": 'RNG',
  "Ring of Butcher": 'DRU',
  "Ring of Feerrott": 'DRU',
  "Ring of Karana": 'DRU',
  "Ring of Lavastorm": 'DRU',
  "Ring of Misty Thicket": 'DRU',
  "Ring of South Ro": 'DRU',
  "Ring of Steamfont": 'DRU',
  "Ring of Stonebrunt": 'DRU',
  "Ring of Surefall Glade": 'DRU',
  "Ring of Toxxulia": 'DRU',
  "Ring of West Commons": 'DRU',
  "Rising Dexterity": 'SHM',
  "Rizlona's Embers": 'BRD',
  "Root": 'CLR/ENC/NEC/PAL/SHM/WIZ',
  "Rune": 'ENC',
  "Sacred Echo": 'CLR',
  "Sacred Word": 'CLR',
  "Sagar's Animation": 'ENC',
  "Sanctuary": 'CLR',
  "Sanity Warp": 'ENC',
  "Savage Spirit": 'DRU',
  "Scale of Wolf": 'DRU/SHM',
  "Scale Skin": 'BST/SHM',
  "Scent of Darkness": 'NEC',
  "Scent of Dusk": 'NEC',
  "Scent of Shadow": 'NEC',
  "Scorching Arrow": 'RNG',
  "Scourge": 'NEC/SHM',
  "Scream of Death": 'SHD',
  "Scream of Hate": 'SHD',
  "Scream of Pain": 'SHD',
  "Screaming Terror": 'NEC',
  "Scythe of Darkness": 'SHD',
  "Searing Arrow": 'RNG',
  "See Invisible": 'DRU/ENC/MAG/RNG/WIZ',
  "Selo's Accelerando": 'BRD',
  "Selo's Accelerating Chorus": 'BRD',
  "Selo's Chords of Cessation": 'BRD',
  "Selo's Consonant Chain": 'BRD',
  "Sense Animals": 'BST/DRU/SHM',
  "Sense Summoned": 'CLR/MAG/WIZ',
  "Sense the Dead": 'CLR/NEC/PAL/SHD',
  "Sentinel": 'ENC',
  "Sermon of the Righteous": 'CLR',
  "Serpent Sight": 'BST/ENC/SHM',
  "Sha's Lethargy": 'BST',
  "Shackle of Bone": 'NEC',
  "Shackle of Spirit": 'NEC',
  "Shade": 'ENC',
  "Shadow": 'ENC',
  "Shadow Compact": 'NEC',
  "Shadow Sight": 'NEC/SHD',
  "Shadow Step": 'NEC/SHD/WIZ',
  "Shadow Vortex": 'NEC/SHD',
  "Shalee's Animation": 'ENC',
  "Shallow Breath": 'ENC',
  "Share Form of the Great Wolf": 'DRU',
  "Share Wolf Form": 'DRU',
  "Sharik's Replenishing": 'BST',
  "Shauri's Sonorous Clouding": 'BRD',
  "Shield of Barbs": 'DRU',
  "Shield of Brambles": 'DRU/RNG',
  "Shield of Fire": 'MAG',
  "Shield of Flame": 'MAG',
  "Shield of Lava": 'MAG',
  "Shield of Song": 'BRD',
  "Shield of Spikes": 'DRU',
  "Shield of Thistles": 'DRU/RNG',
  "Shield of Thorns (Spell)": 'DRU',
  "Shield of Words": 'CLR',
  "Shielding": 'ENC/MAG/NEC/WIZ',
  "Shieldskin": 'NEC/SHD/WIZ',
  "Shifting Shield": 'SHM',
  "Shifting Sight": 'ENC/WIZ',
  "Shiftless Deeds": 'ENC',
  "Shock of Blades": 'MAG',
  "Shock of Fire": 'WIZ',
  "Shock of Flame": 'MAG',
  "Shock of Frost": 'WIZ',
  "Shock of Ice": 'WIZ',
  "Shock of Lightning": 'WIZ',
  "Shock of Poison": 'NEC',
  "Shock of Spikes": 'MAG',
  "Shock of Swords": 'MAG',
  "Shock of the Tainted": 'SHM',
  "Shock of Venom": 'SHM',
  "Shock Spiral of Al'Kabor": 'WIZ',
  "Shrink": 'BST/SHM',
  "Shroud of Hate": 'SHD',
  "Shroud of Pain": 'SHD',
  "Sicken": 'BST/SHM',
  "Sight": 'WIZ',
  "Sight Graft": 'NEC',
  "Sionachie's Dreams": 'BRD',
  "Siphon Life": 'NEC/SHD',
  "Siphon Strength": 'NEC/SHD',
  "Sisna's Animation": 'ENC',
  "Skin Like Diamond": 'DRU',
  "Skin Like Nature": 'DRU',
  "Skin Like Rock": 'DRU/RNG',
  "Skin Like Steel": 'DRU/RNG',
  "Skin Like Wood": 'DRU/RNG',
  "Slugs Healing": 'SHM',
  "Smite": 'CLR/PAL',
  "Snails Healing": 'SHM',
  "Snare": 'DRU/RNG',
  "Solon's Bravura": 'BRD',
  "Solon's Song of the Sirens": 'BRD',
  "Song of Sustenance": 'BRD',
  "Song: Melody of Ervaj": 'BRD',
  "Soothe": 'CLR/ENC/PAL',
  "Sound of Force": 'CLR',
  "Spear of Disease": 'SHD',
  "Spear of Pain": 'SHD',
  "Spear of Warding": 'MAG',
  "Sphere of Light": 'WIZ',
  "Spike of Disease": 'SHD',
  "Spikecoat": 'DRU/RNG',
  "Spirit Armor": 'CLR/NEC/PAL',
  "Spirit of Bear": 'BST/SHM',
  "Spirit of Bih`Li": 'SHM',
  "Spirit of Cat": 'SHM',
  "Spirit of Cheetah": 'DRU/SHM',
  "Spirit of Herikol": 'BST',
  "Spirit of Inferno": 'BST',
  "Spirit of Kashek": 'BST',
  "Spirit of Keshuval": 'BST',
  "Spirit of Khaliz": 'BST',
  "Spirit of Lightning": 'BST',
  "Spirit of Monkey": 'BST/SHM',
  "Spirit of Ox": 'BST/SHM',
  "Spirit of Sharik": 'BST',
  "Spirit of Snake": 'SHM',
  "Spirit of the Blizzard": 'BST',
  "Spirit of the Puma": 'SHM',
  "Spirit of the Scorpion": 'BST',
  "Spirit of the Shrew": 'BST/DRU/RNG/SHM',
  "Spirit of Vermin": 'BST',
  "Spirit of Wolf": 'BST/DRU/RNG/SHM',
  "Spirit of Yekan": 'BST',
  "Spirit Pouch": 'SHM',
  "Spirit Quickening": 'SHM',
  "Spirit Salve": 'BST/SHM',
  "Spirit Sight": 'BST/SHM',
  "Spirit Strength": 'BST/SHM',
  "Spirit Strike": 'BST/SHM',
  "Spirit Tap": 'NEC/SHD',
  "Spiritual Brawn": 'BST',
  "Spiritual Light": 'BST',
  "Spook the Dead": 'CLR/NEC/PAL/SHD',
  "Sprouting Heal": 'DRU',
  "Staff of Runes": 'MAG',
  "Staff of Symbols": 'MAG',
  "Staff of Tracing": 'MAG',
  "Staff of Warding": 'MAG',
  "Stamina": 'SHM',
  "Starfire": 'DRU',
  "Starshine": 'DRU',
  "Steelskin": 'NEC/WIZ',
  "Stinging Swarm": 'DRU/RNG',
  "Stoicism": 'SHM',
  "Stonebrunt Gate": 'WIZ',
  "Stonebrunt Portal": 'WIZ',
  "Storm Strength": 'DRU',
  "Strength": 'SHM',
  "Strength of Earth": 'DRU/RNG',
  "Strength of Stone": 'DRU',
  "Strengthen": 'BST/ENC/SHM',
  "Strengthen Death": 'SHD',
  "Strike": 'CLR/PAL',
  "Strip Enchantment": 'ENC',
  "Stun": 'CLR/PAL',
  "Succor: Butcherblock": 'DRU',
  "Succor: East Karana": 'DRU',
  "Succor: Lavastorm": 'DRU',
  "Succor: North Karana": 'DRU',
  "Succor: South Ro": 'DRU',
  "Suffocate": 'ENC',
  "Suffocating Sphere": 'ENC',
  "Summon Arrows": 'MAG',
  "Summon Bandages": 'MAG',
  "Summon Brass Choker": 'MAG',
  "Summon Coldstone": 'MAG',
  "Summon Companion": 'BST/DRU/ENC/MAG/NEC/SHM',
  "Summon Dagger": 'MAG',
  "Summon Dead": 'NEC/SHD',
  "Summon Drink": 'BST/CLR/DRU/MAG/SHM',
  "Summon Elemental Blanket": 'MAG',
  "Summon Elemental Defender": 'MAG',
  "Summon Fang": 'MAG',
  "Summon Food": 'BST/CLR/DRU/MAG/SHM',
  "Summon Golden Choker": 'MAG',
  "Summon Heatstone": 'MAG',
  "Summon Jade Bracelet": 'MAG',
  "Summon Leather Mantle": 'MAG',
  "Summon Linen Mantle": 'MAG',
  "Summon Opal Bracelet": 'MAG',
  "Summon Orb": 'MAG',
  "Summon Phantom Chain": 'MAG',
  "Summon Phantom Leather": 'MAG',
  "Summon Phantom Plate": 'MAG',
  "Summon Ring of Flight": 'MAG',
  "Summon Shard of the Core": 'MAG',
  "Summon Shiny Bauble": 'MAG',
  "Summon Silver Choker": 'MAG',
  "Summon Stone Bracelet": 'MAG',
  "Summon Tarnished Bauble": 'MAG',
  "Summon Throwing Dagger": 'MAG',
  "Summon Tiny Ring": 'MAG',
  "Summon Twisted Ring": 'MAG',
  "Summon Waterstone": 'MAG',
  "Summon Wisp": 'MAG',
  "Summon Wooden Bracelet": 'MAG',
  "Summon: Orb of Exploration": 'MAG',
  "Summoning: Air": 'MAG',
  "Summoning: Earth": 'MAG',
  "Summoning: Fire": 'MAG',
  "Summoning: Water": 'MAG',
  "Sunbeam": 'DRU',
  "Superior Camouflage": 'DRU/RNG',
  "Superior Healing": 'CLR/DRU/PAL/SHM',
  "Supernova": 'WIZ',
  "Surge of Enfeeblement": 'NEC',
  "Swarm of Pain": 'RNG',
  "Swift Like The Wind": 'ENC',
  "Sword of Runes": 'MAG',
  "Symbol of Naltron": 'CLR',
  "Symbol of Pinzarn": 'CLR/PAL',
  "Symbol of Ryltan": 'CLR/PAL',
  "Symbol of Transal": 'CLR/PAL',
  "Sympathetic Aura": 'ENC',
  "Syvelian's Anti-Magic Aria": 'BRD',
  "Tagar's Insects": 'SHM',
  "Tainted Breath": 'BST/SHM',
  "Talisman of Altuna": 'SHM',
  "Talisman of Jasinth": 'SHM',
  "Talisman of the Beast": 'SHM',
  "Talisman of Tnarg": 'SHM',
  "Tame Spirit": 'BST',
  "Tangling Weeds": 'DRU/RNG',
  "Taper Enchantment": 'ENC',
  "Tarew's Aquatic Ayre": 'BRD',
  "Tashani": 'ENC',
  "Tashania": 'ENC',
  "Tashina": 'ENC',
  "Tepid Deeds": 'ENC',
  "Terror of Darkness": 'SHD',
  "Terror of Shadows": 'SHD',
  "Terrorize Animal": 'DRU',
  "Theft of Thought": 'ENC',
  "Thicken Mana": 'ENC',
  "Thistlecoat": 'DRU/RNG',
  "Thorncoat": 'DRU',
  "Thunder of Karana": 'PAL',
  "Thunder Strike": 'WIZ',
  "Thunderclap": 'WIZ',
  "Tiny Companion": 'BST/DRU/ENC/MAG/NEC/SHD/SHM',
  "Tishan's Clash": 'WIZ',
  "Togor's Insects": 'SHM',
  "Torbas Acid Blast": 'NEC',
  "Torbas Poison Blast": 'NEC',
  "Tortoises Healing": 'SHM',
  "Toxxulia Gate": 'WIZ',
  "Toxxulia Portal": 'WIZ',
  "Translocate": 'WIZ',
  "Translocate: Cazic Temple": 'WIZ',
  "Translocate: Greater Faydark": 'WIZ',
  "Translocate: Nektulos": 'WIZ',
  "Translocate: North Karana": 'WIZ',
  "Translocate: North Ro": 'WIZ',
  "Translocate: Stonebrunt": 'WIZ',
  "Translocate: Toxxulia": 'WIZ',
  "Translocate: West Commons": 'WIZ',
  "Translocate: West Karana": 'WIZ',
  "Treeform": 'DRU',
  "Tremor": 'CLR/DRU',
  "True North": 'CLR/ENC/MAG/NEC/PAL/SHM/WIZ',
  "Tumultuous Strength": 'SHM',
  "Turning of the Unnatural": 'CLR',
  "Turtle Skin": 'BST/SHM',
  "Tuyen's Chant of Disease": 'BRD',
  "Tuyen's Chant of Flame": 'BRD',
  "Tuyen's Chant of Frost": 'BRD',
  "Tuyen's Chant of Poison": 'BRD',
  "Uleen's Animation": 'ENC',
  "Ultravision": 'ENC/SHM',
  "Upheaval": 'DRU',
  "Valor": 'CLR/PAL',
  "Valor of Marr": 'PAL',
  "Vampiric Curse": 'NEC',
  "Vampiric Embrace": 'NEC/SHD',
  "Vengeance of the Wild": 'DRU',
  "Venom of the Snake": 'NEC/SHM',
  "Verses of Victory": 'BRD',
  "Vigilant Spirit": 'SHM',
  "Vigor of Zehkes": 'BST',
  "Vilia's Verses of Celerity": 'BRD',
  "Vision": 'SHM',
  "Vision Shift": 'WIZ',
  "Voice Graft": 'NEC',
  "Voice of Darkness": 'SHD',
  "Voice of Shadows": 'SHD',
  "Walking Sleep": 'SHM',
  "Wandering Mind": 'ENC',
  "Ward of Alendar": 'ENC',
  "Ward of Calliav": 'BST/MAG/NEC',
  "Ward of Calrena": 'WIZ',
  "Ward of the Divine": 'CLR',
  "Ward of Vie": 'CLR',
  "Ward Summoned": 'CLR/DRU/MAG/RNG',
  "Ward Undead": 'CLR/NEC/PAL/SHD',
  "Wave of Enfeeblement": 'NEC/SHD',
  "Wave of Fear": 'CLR',
  "Wave of Life": 'PAL',
  "Weaken": 'ENC',
  "Weakness": 'ENC',
  "West Commons Gate": 'WIZ',
  "West Commons Portal": 'WIZ',
  "West Karana Gate": 'WIZ',
  "West Karana Portal": 'WIZ',
  "Whirl Till You Hurl": 'ENC',
  "Whirling Wind": 'DRU',
  "Wild Spirit": 'BST',
  "Winter's Roar": 'SHM',
  "Wolf Form": 'DRU/RNG',
  "Word Divine": 'CLR',
  "Word of Healing": 'CLR',
  "Word of Health": 'CLR',
  "Word of Pain": 'CLR',
  "Word of Shadow": 'CLR/NEC',
  "Word of Souls": 'CLR/NEC',
  "Word of Spirit": 'CLR/NEC/SHD',
  "Wrath": 'CLR/PAL',
  "Wrath of Ap'Sagor": 'WIZ',
  "Yaulp": 'CLR/PAL',
  "Yegoreff's Animation": 'ENC',
  "Yekan's Quickening": 'BST',
  "Yekan's Recovery": 'BST',
  "Yonder": 'WIZ',
  "Zephyr: Butcherblock": 'DRU',
  "Zephyr: Feerrott": 'DRU',
  "Zephyr: Lavastorm": 'DRU',
  "Zephyr: Misty Thicket": 'DRU',
  "Zephyr: North Karana": 'DRU',
  "Zephyr: South Ro": 'DRU',
  "Zephyr: Steamfont": 'DRU',
  "Zephyr: Stonebrunt": 'DRU',
  "Zephyr: Surefall Glade": 'DRU',
  "Zephyr: Toxxulia": 'DRU',
  "Zephyr: West Commons": 'DRU',
};

/**
 * Índice de consulta, en minúsculas.
 *
 * EL LOG NO ESCRIBE LOS NOMBRES CON LA MISMA CAJA QUE LA WIKI. Medido: el
 * registro escribe «Invisibility Versus Undead» y la wiki «Invisibility versus
 * Undead», así que 22 lanzamientos no casaban con nada y el hechizo salía como
 * desconocido. Comparando sin caja, esa clase entera de fallo desaparece —y es
 * el mismo arreglo que ya se le hizo a los nombres de enemigo, por el mismo
 * motivo: enumerar variantes no escala, comparar sin caja sí.
 */
const INDICE = new Map();
for (const [h, c] of Object.entries(HECHIZOS)) INDICE.set(h.toLowerCase(), c.split('/'));

/** Acciones que no son hechizos y que sí prueban clase. Se llena en `ACCIONES`. */
const ACCIONES = new Map();

/**
 * ¿Esta acción demuestra que una clase estaba activa?
 *
 * Sólo si la tiene UNA de las clases conocidas. Una acción compartida no
 * demuestra nada y devuelve null, igual que una que no esté en ninguna lista:
 * callar ante lo desconocido es lo que impide que una laguna se lea como una
 * prueba.
 *
 * El rango se quita AQUÍ DENTRO, y no en quien llama. Antes había que acordarse
 * de pasar `baseSpell()` antes, y no se hacía: `Drain Spirit X` no casaba con
 * `Drain Spirit` y 2.041 lanzamientos no probaban nada. Un requisito que hay
 * que recordar en cada sitio es un requisito que se incumple en alguno.
 *
 * @returns {string|null} código de clase, o null
 */
export function proofOf(accion) {
  const n = String(accion ?? '').trim();
  if (!n) return null;
  const a = ACCIONES.get(n.toLowerCase());
  if (a) return a.length === 1 ? a[0] : null;
  const d = INDICE.get(baseSpell(n).toLowerCase());
  return d && d.length === 1 ? d[0] : null;
}

/** Para la interfaz: qué clases tienen esto, de las conocidas. */
export function ownersOf(accion) {
  const n = String(accion ?? '').trim();
  if (!n) return [];
  return (ACCIONES.get(n.toLowerCase()) ?? INDICE.get(baseSpell(n).toLowerCase()) ?? []).slice();
}

/** Todo lo que prueba una clase. Para pruebas y para la interfaz. */
ownersOf.byClass = (clase) => [
  ...Object.entries(HECHIZOS).filter(([, c]) => c.split('/').includes(clase)).map(([h]) => h),
  ...[...ACCIONES].filter(([, c]) => c.includes(clase)).map(([a]) => a),
];

/** La procedencia, para que la interfaz pueda decirla sin inventársela. */
export const FUENTE = {
  origen: 'eqlwiki.com',
  consultado: '2026-08-10',
  paginas: 12,
  tipo: 'consultado',
};
